export const authConsts = {
	LOGIN_REQUEST: 'LOGIN_REQUEST',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',
	GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
	GET_PROFILE: 'GET_PROFILE',
	GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
	EDIT_PROFILE_ERROR: 'EDIT_PROFILE_ERROR',
	EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
	EDIT_PROFILE_REQUEST: 'EDIT_PROFILE_REQUEST',
	LOGOUT: 'LOGOUT',
	FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
	FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
	FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
	CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
	CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
	CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE'
}