server:
  port: 8080

spring:
  datasource:
    password: user
    url: jdbc:postgresql://localhost:5432/db
    username: user
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /doc

jwt:
  secret: adfasfsfsfdsf
  secretRefresh: ffsdfsadfsadfsdaf
  secretPasswordReset: fsddfsfdafasfdgd
  secretPasswordUpdate: gdfgfgdsfgwgedag
  expiration: 7200
  expirationRefresh: 604800
  expirationPasswordReset: 86400
  expirationPasswordUpdate: 3600
  header: Authorization

url:
  server: http://localhost:8080
  client: http://localhost:3000
clientChangePasswordPath: changePassword
serverChangePasswordPath: api/v1/auth/resetPassword
